# Generated by Django 4.2.8 on 2024-06-01 08:20

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('status', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('PL', 'Playing')], default='OF', max_length=2, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secret Key')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two Factor Enabled')),
                ('last_2fa_login', models.DateTimeField(blank=True, null=True, verbose_name='Last 2FA Login')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_to)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
