# Generated by Django 4.2.8 on 2024-05-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
    ]
