# Generated by Django 4.2.8 on 2024-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_2fa_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider'),
        ),
    ]
