# Generated by Django 4.2.8 on 2024-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_paddle_type_user_table_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='table_theme',
            field=models.CharField(choices=[('C', 'Classic'), ('S', 'Standard'), ('F', 'Football')], default='S', max_length=1, verbose_name='Table Theme'),
        ),
    ]
