# Generated by Django 4.2.8 on 2024-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_2fa_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created At'),
        ),
    ]
