# Generated by Django 4.2.8 on 2024-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider'),
        ),
    ]
