# Generated by Django 4.2.8 on 2024-06-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_userstats_user'),
        ('accounts', '0003_alter_user_table_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.userstats'),
        ),
    ]
