# Generated by Django 4.2.8 on 2024-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
