version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: veca-server
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    restart: always
