version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: veca-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
      - ./conf/certs:/etc/nginx/certs
    restart: always
