FROM python:3.9.5

WORKDIR /app

COPY . .

ENV DJANGO_SETTINGS_MODULE=backend.settings

ENTRYPOINT ["./backend-entrypoint.sh"]

CMD ["daphne", "-e", "ssl:8443:privateKey=/app/certs/yelaissa.key:certKey=/app/certs/yelaissa.crt", "backend.asgi:application"]
