# Generated by Django 4.2.8 on 2024-05-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
