# Generated by Django 4.2.8 on 2024-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentmatch_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_number',
            field=models.IntegerField(null=True),
        ),
    ]
