# Generated by Django 4.2.8 on 2024-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
