# Generated by Django 4.2.8 on 2024-06-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('S', 'Starting'), ('W', 'Waiting'), ('O', 'Ongoing'), ('F', 'Finished')], default='W', max_length=1, verbose_name='Status')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchemaking_player1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchemaking_player2', to=settings.AUTH_USER_MODEL)),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchemaking_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
