# Generated by Django 4.2.8 on 2024-06-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchemaking', '0004_matchmaking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 2, 15, 11, 27, 645035, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
