# Generated by Django 4.2.8 on 2024-06-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0002_alter_matchmaking_winner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmaking',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchmaking',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchmaking',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
