# Generated by Django 4.2.8 on 2024-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_matchmaking_winner_id_matchmaking_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
