# Generated by Django 4.2.8 on 2024-06-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_rename_player1_matchmaking_user1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchmaking',
            old_name='user1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='matchmaking',
            old_name='user2',
            new_name='player2',
        ),
    ]
