# Generated by Django 4.2.8 on 2024-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_rename_user1_matchmaking_player1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchmaking',
            old_name='player1',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='matchmaking',
            old_name='player2',
            new_name='user2',
        ),
    ]
