# Generated by Django 4.2.8 on 2024-06-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_rename_player1_matchmaking_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmaking',
            name='created_at',
        ),
    ]
