# Generated by Django 4.2.8 on 2024-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_remove_matchmaking_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchmaking',
            old_name='user1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='matchmaking',
            old_name='user2',
            new_name='player2',
        ),
        migrations.AddField(
            model_name='matchmaking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
