# Generated by Django 4.2.8 on 2024-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secret Key'),
        ),
    ]
