# Generated by Django 4.2.8 on 2024-05-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_2fa_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last 2FA Login'),
        ),
    ]
