# Generated by Django 4.2.8 on 2024-06-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_userstats_friends_count_alter_userstats_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
    ]
